# sourcedir needs submodule initialization (to compile googletest)
# - git submodule update --init --recursive

image: node:6.10.0

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    
stages:
  - build

.base:
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - artifacts
    expire_in: 1 hour

.base:unix:
  extends: .base
# Important! Do not remove this after_script as the VM will live for 12 hours before being destroyed!
  after_script:
    - /opt/post_build_script.sh

.base:windows:
  extends: .base
# Important! Do not remove this after_script as the VM will live for 12 hours before being destroyed!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build:mac:
  extends: .base:unix
  stage: build
  tags:
    - buildfarm
    - darwin
  script:
    - ./build.sh

build:windows:
  extends: .base:windows
  stage: build
  tags:
    - buildfarm
    - windows
  script:
    - build.cmd

build:linux:
  extends: .base:unix
  stage: build
  tags:
    - buildfarm
    - linux
  script:
    - ./build.sh

#push_to_packman_staging:
#  stage: push_to_packman_staging
#  only:
#    - /^v\d*$/
#  except:
#    - branches
#  script:
#    - curl -u $USER_NAME:$API_KEY https://staging-packages.unity.com/auth > .npmrc
#    - npm publish
